# -*- coding: utf-8 -*-
"""3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

def calcular_fatorial(numero):
    fatorial = 1
    while numero > 1:
        fatorial *= numero
        numero -= 1
    return fatorial

def solicitar_numero():
    while True:
        try:
            numero = int(input("Digite um número para calcular o fatorial: "))
            if numero >= 0:
                return numero
            else:
                print("Por favor, digite um número positivo.")
        except ValueError:
            print("Entrada inválida. Por favor, digite um número inteiro.")

numero = solicitar_numero()

fatorial = calcular_fatorial(numero)

print(f"O fatorial de {numero} é {fatorial}.")