# -*- coding: utf-8 -*-
"""0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

numero = int(input("Digite um número: "))

if numero % 2 == 0:
    print('Esse número é Par.')
else:
    print('Esse número é Ímpar.')