# -*- coding: utf-8 -*-
"""0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

raio = float(input('Digite o raio do círculo que você deseja descobrir a área: '))

area = 3.14 * (raio ** 2)

print(f'A área do círculo é {area}')