# -*- coding: utf-8 -*-
"""0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

amount = 0

for i in range(1, 101):
    if (i % 2 == 0):
        amount += i

print(f"A soma dos números pares é: {amount}")