# -*- coding: utf-8 -*-
"""0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

num1 = int(input("Digite o primeiro número: "))
num2 = int(input("Digite o segundo número: "))
operation = input("Digite qual a operação que você deseja. ex (+ | - | * | /): ")

match operation:
    case '+':
        result = num1 + num2
        print(f"O resultado da soma é: {result}")
    case '-':
        result = num1 - num2
        print(f"O resultado da subtração é: {result}")
    case '*':
        result = num1 * num2
        print(f"O resultado da multiplicação é: {result}")
    case '/':
        result = num1 / num2
        print(f"O resultado da divisão é: {result}")
    case _:
        print("Operação inválida")