# -*- coding: utf-8 -*-
"""0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

num = int(input("Digite um número: "))

amount = num * (num + 1) // 2

print(f"A soma dos 'n' primeiros números é: {amount}")