# -*- coding: utf-8 -*-
"""0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

word = input("digite um palavra: ")
inverted_word = ""

for i in range(len(word) -1, -1, -1):
    inverted_word += word[i]

print(f"A palavra na forma invertida é: {inverted_word}")