# -*- coding: utf-8 -*-
"""0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

frase = input("Digite uma frase qualquer: ")

palavras = []
index = 0

for i in range(0, len(frase)):
    if frase[i] == ' ':
        palavras.append(frase[index:i])
        index = i

print(f"A quantidade de palavras na frase é: {len(palavras)}")