# -*- coding: utf-8 -*-
"""3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

def temp(celsius):
    fahrenheit = (celsius * 9/5) + 32
    kelvin = celsius + 273.15
    return fahrenheit, kelvin

celsius = float(input("Digite a temperatura em Celsius: "))

fahrenheit, kelvin = temp(celsius)

print(f"{celsius}°C é igual a {fahrenheit}°F e {kelvin} K.")