# -*- coding: utf-8 -*-
"""0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

lista = []
i = 0

while i != -1:
    a = int(input("Digite um número para colocar na lista(ou -1 para sair) "))
    i = a
    if a != -1:
        lista.append(a)

min = min(lista)
mai = max(lista)
soma = sum(lista)
quantidade = len(lista)

media = soma / quantidade

print(f"O min número da lista é o: {min} o mai é o :{mai} A média dos números: {media}")