# -*- coding: utf-8 -*-
"""0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

print('Cálculo de IMC')

peso = float(input('Peso em kg: '))
altura = float(input('Altura em metros. (Ex 1.85). '))

imc = peso / (altura ** 2)

print(f'O IMC é de: {imc:.2f}')