# -*- coding: utf-8 -*-
"""0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

print('Palíndromo')

frase = input('Digite uma frase: ')

print(f'A frase "{frase}" ', end='')

if frase.lower() == frase[::-1].lower():
    print('é um palíndromo.')
else:
    print('não é um palíndromo.')