# -*- coding: utf-8 -*-
"""0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

print('Tabuada')

n = int(input('Digite um número: '))

for i in range(1, 11):
    print(f'{n} x {i} = {n * i}')