# -*- coding: utf-8 -*-
"""0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

frase = input("Digite uma frase ")

vogais= ("aAeEiIoOuU")
contador= 0
for letra in frase:
 if letra in vogais:
  contador +=1

print(f"A frase {frase} tem {contador} vogais")