# -*- coding: utf-8 -*-
"""0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

notas = 0
grade = 0
contador = 0

while grade != -1:
  grade = float(input("Escreva as notas a seguir: (Escreva -1 para terminar): "))
  if grade != -1:
    notas += grade
    contador += 1

media = notas/contador

print(f"A médi das {contador} notas digitadas é {media:.2f}.")