# -*- coding: utf-8 -*-
"""0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

n = int(input("Digite um numero: "))

inicio = [0, 1]
for i in range(2, n):
    proximo = inicio[i-1] + inicio[i-2]
    inicio.append(proximo)


fibo = [inicio[i] for i in range(n)]

print(f"Os primeiros {n} números da sequência de Fibonacci são: {fibo}")