# -*- coding: utf-8 -*-
"""0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

numeros = list()

for i in range (1, 4):
    numero = int(input("Digite um número: "))
    numeros.append(numero)

for i in range(len(numeros)):
    for indice_atual in range(len(numeros) - 1):
        if numeros[indice_atual] > numeros[indice_atual + 1]:
            numeros[indice_atual], numeros[indice_atual + 1] = numeros[indice_atual + 1], numeros[indice_atual]

print(numeros)