# -*- coding: utf-8 -*-
"""1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

filme = input('Qual o nome do seu filme favorito? ')
ano = input('Qual que foi lançado esse filme? ')

print(f'O filme {filme} lançado em {ano} é um ótimo filme.')