# -*- coding: utf-8 -*-
"""3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

num1 = float(input('Digite um número: '))
num2 = float(input('Digite outro número: '))

print(f'>>Soma: {num1 + num2}, >>Subtração: {num1 - num2}, >>Multiplicação: {num1 * num2}, >>2Divisão: {num1 / num2}')