# -*- coding: utf-8 -*-
"""3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

temp = float(input('Escreva uma temperatura em Celsius: '))

print(f'A temperatura {temp} °C é ', end='')

if temp > 30:
    print(' quente.')
elif temp < 15:
    print('fria.')
else:
    print('agradável.')