# -*- coding: utf-8 -*-
"""3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

soma = 0

while True:
    num = float(input('Digite um número pra somar (0 pra sair)'))

    if num == 0:
        break

    soma += num

print(f'A soma dos números digitados é: {soma}')