# -*- coding: utf-8 -*-
"""3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

lista = []

print('Minha lista de compras')
while True:
    item = input("Digite um novo item ou 'ok' para finalizar: ")

    if item == 'ok':
        break

    lista.append(item)

print('A lista de compras completa é:')
for item in lista:
    print(f'  * {item}')