# -*- coding: utf-8 -*-
"""3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

def numb (numero):
    if numero % 2 == 0:
        return print("Este numero é par!")
    else:
        return print("Esté numero é impar!")
num=int(input("Digite um número: "))
numb (num)