# -*- coding: utf-8 -*-
"""3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fe--5tdS527Kjzw6O4frHxwOT-rUDRd4
"""

frase = str(input("Digite uma frase ")).casefold()

letra = str(input("Digite uma letra: ")).casefold()

contagem = frase.count(letra)

print(f"A letra {letra} apareceu {contagem} vezes.")